# -*- coding: utf-8 -*-
"""Alertsystem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPHd0ztvV63kP-df0KYbNDq-TmhIHy3P
"""

def alert_emotion_distribution(predictions, threshold=0.3):
    from collections import Counter
    total = len(predictions)
    counts = Counter(predictions)
    for emotion, count in counts.items():
        if count / total > threshold:
            print(f"⚠️ ALERT: High proportion of {emotion.upper()} tweets detected!")