# -*- coding: utf-8 -*-
"""Clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYPkt6yZb27_poD_ilpvqsjCoYKb8K6Z
"""

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

def run_clustering(tfidf_vectors, num_clusters=6):
    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
    labels = kmeans.fit_predict(tfidf_vectors)

    # Visualize with PCA
    reduced = PCA(n_components=2).fit_transform(tfidf_vectors.toarray())
    plt.scatter(reduced[:,0], reduced[:,1], c=labels, cmap='viridis')
    plt.title("KMeans Clustering of Tweets")
    plt.savefig("outputs/clustering_plot.png")
    return labels