# -*- coding: utf-8 -*-
"""Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbFHk6EZ4S29kmbow_hK0bRQp1ybp4Ny
"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    text = re.sub(r"http\S+|@\w+|#\w+", "", text)  # Remove links, mentions, hashtags
    text = re.sub(r"[^a-zA-Z\s]", "", text).lower()
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)