# -*- coding: utf-8 -*-
"""scraper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3rvV1FgG2c0mUcogCHu-y3Q8dLq1XVY
"""

pip install snscrape

import snscrape.modules.twitter as sntwitter
import pandas as pd

def scrape_tweets(query, limit=100):
    tweets = []
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
        if i >= limit:
            break
        tweets.append([tweet.date, tweet.content])
    return pd.DataFrame(tweets, columns=["date", "text"])