# -*- coding: utf-8 -*-
"""SVM-model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxp_aiMafcsN4wySy9rdMzcHjhAmkP89
"""

import joblib
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

def train_svm(X_text, y):
    vectorizer = TfidfVectorizer(max_features=5000)
    X = vectorizer.fit_transform(X_text)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = SVC(kernel="linear", probability=True)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    with open("outputs/classification_report.txt", "w") as f:
        f.write(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title("Confusion Matrix")
    plt.savefig("outputs/confusion_matrix.png")

    joblib.dump((model, vectorizer), "models/svm_model.pkl")